name: gozat360
description: Gozat360 - is ilanlari ve ikinci el ilanlarini bir araya getiren Flutter uygulamasi
publish_to: "none"
version: 0.4.0+4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  
  http: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    
    
    
    - file_00000000e26c81f58631d89abd23397f.png
    - file_0000000033c881f59f1f7b2fe62adcf7.png
    - file_000000006fcc821194f1d6a3784e8361.png
